---
title: "MGMTMFE 405 - Project 7"
author: "Yanxiang Zhao"
date: "February 28, 2019"
output: pdf_document
---
# Set up
```{R}
source("finiteDiff.r")
source("bsm.r")
```

# Problem 1
For this problem, I used the $\Delta x = \sigma\sqrt{\Delta t}$.
```{R}
# set parameters
s0 <- 10
k <- 10
r <- 0.04
sig <- 0.2
t <- 0.5
dt <- 0.002
dx <- sig*sqrt(dt)
```

## i. Find the values:

```{R}
# i. Values
# (a) Explicit Finite-Difference Method
Pa <- efd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# (b) Implicit Finite-Difference Method
Pb <- ifd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# (c) Crank-Nicolson Finite-Difference Method
Pc <- cnfd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# output
c(EFD = Pa, IFD = Pb, CNFE = Pc)
```

## i. Compare the errors against BSM value:
```{R}
# ii. Comparison
s0 <- 4:16
p_edf <- p_idf <- p_cndf <- p_bs <- vector()
for (i in 1:length(s0)){
  p_edf[i] <- efd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_idf[i] <- ifd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_cndf[i] <- cnfd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_bs[i] <- bsPut(s0[i], t, k, r, sig)
}
err <- cbind(p_edf, p_idf, p_cndf)-p_bs
rownames(err) <- s0
err
```
  
From the table above, we see that the errors are really small over all. The explicit finite-difference method has the highest sum of squred errors (4.603896e-07). The implicit finite-difference method has the second highest sum of squred errors (4.107216e-07). And the Crank-Nicolson finite-difference method has the lowest sum of squred errors (7.933473e-08). Overall, the Crank-Nicolson's methond is better than the other two finite-difference methods.   
  
```{R}
# plot
matplot(s0, abs(err), type ="l", lwd = 3, lty=1, main = "Absolute error against BSM Model")
legend("topleft", legend = colnames(err), lwd = 3, col = 1:3)
```

To further understand the estimate errors, I plot the absolute values of the errors agains the stock price. The graph above shows that the estimate errors are the highest when the options are at the money. The errors becomes lower as the options move further in-the-money or out-of-the-money. From the graph, it also shows that the Crank-NNicolson's method has the overall lowest errors. 

# Problem 2
For this problem, I used $\Delta S = 0.25$.  
```{R}
# set parameters
s0 <- 10
k <- 10
r <- 0.04
sig <- 0.2
t <- 0.5
dt <- 0.002
ds <- 0.25
# i. Values
# (a) Explicit Finite-Difference Method
Pa <- efd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# (b) Implicit Finite-Difference Method
Pb <- ifd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# (c) Crank-Nicolson Finite-Difference Method
Pc <- cnfd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# output
c(EFD = Pa, IFD = Pb, CNFE = Pc)
```
   
## i. Find the values:
```{R}
# (a) Explicit Finite-Difference Method
Ca <- efd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pa <- efd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# (b) Implicit Finite-Difference Method
Cb <- ifd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pb <- ifd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# (c) Crank-Nicolson Finite-Difference Method
Cc <- cnfd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pc <- cnfd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# output
cbind(EFD = c(call = Ca, put = Pa), IFD = c(Cb, Pb), CNFE = c(Cc, Pc))
```

# ii. Plot the values
```{R}
s0 <- 4:16
c_edf2 <- c_idf2 <- c_cndf2 <- vector()
p_edf2 <- p_idf2 <- p_cndf2 <- vector()
for (i in 1:length(s0)){
  # calls
  c_edf2[i] <- efd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  c_idf2[i] <- ifd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  c_cndf2[i] <- cnfd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  # puts
  p_edf2[i] <- efd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  p_idf2[i] <- ifd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  p_cndf2[i] <- cnfd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
}
matplot(s0, cbind(c_edf2, c_idf2, c_cndf2), type ="l", lwd = 1, lty=1,
        main = "Call Prices", xlab = "Stock price", ylab = "Call Price")
legend("topleft", legend = c("EDF", "IDF", "CNDF"), lwd = 1, col = 1:3)
matplot(s0, cbind(p_edf2, p_idf2, p_cndf2), type ="l", lwd = 1, lty=1,
        main = "Put Prices", xlab = "Stock price", ylab = "Put Price")
legend("topright", legend = c("EDF", "IDF", "CNDF"), lwd = 1, col = 1:3)

```

\newpage

# Additional tables and plots 

## Problem 1
Now I used different $\Delta x$ to test for the results. The errors get larger as the $\Delta x$s become larger. The **EFD method** becomes a better estimator with the larger $\Delta x$.  

$\Delta x = \sigma\sqrt{3*\Delta t}$:
```{R echo = FALSE}
# set parameters
s0 <- 10
k <- 10
r <- 0.04
sig <- 0.2
t <- 0.5
dt <- 0.002
dx <- sig*sqrt(3*dt)

# i. Values
# (a) Explicit Finite-Difference Method
Pa <- efd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# (b) Implicit Finite-Difference Method
Pb <- ifd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# (c) Crank-Nicolson Finite-Difference Method
Pc <- cnfd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# output
c(EFD = Pa, IFD = Pb, CNFE = Pc)

# ii. Comparison
s0 <- 4:16
p_edf <- p_idf <- p_cndf <- p_bs <- vector()
for (i in 1:length(s0)){
  p_edf[i] <- efd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_idf[i] <- ifd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_cndf[i] <- cnfd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_bs[i] <- bsPut(s0[i], t, k, r, sig)
}
err <- cbind(p_edf, p_idf, p_cndf)-p_bs
rownames(err) <- s0
err
# plot
matplot(s0, abs(err), type ="l", lwd = 3, lty=1, main = "Absolute error against BSM Model")
legend("topleft", legend = colnames(err), lwd = 3, col = 1:3)
```

$\Delta x = \sigma\sqrt{4*\Delta t}$
```{R echo = FALSE}
# set parameters
s0 <- 10
k <- 10
r <- 0.04
sig <- 0.2
t <- 0.5
dt <- 0.002
dx <- sig*sqrt(4*dt)

# i. Values
# (a) Explicit Finite-Difference Method
Pa <- efd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# (b) Implicit Finite-Difference Method
Pb <- ifd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# (c) Crank-Nicolson Finite-Difference Method
Pc <- cnfd(type="put", euro=T, s0, k, r, sig, t, dt, dx, log=T)
# output
c(EFD = Pa, IFD = Pb, CNFE = Pc)

# ii. Comparison
s0 <- 4:16
p_edf <- p_idf <- p_cndf <- p_bs <- vector()
for (i in 1:length(s0)){
  p_edf[i] <- efd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_idf[i] <- ifd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_cndf[i] <- cnfd(type="put", euro=T, s0[i], k, r, sig, t, dt, dx, log=T)
  p_bs[i] <- bsPut(s0[i], t, k, r, sig)
}
err <- cbind(p_edf, p_idf, p_cndf)-p_bs
rownames(err) <- s0
err
# plot
matplot(s0, abs(err), type ="l", lwd = 3, lty=1, main = "Absolute error against BSM Model")
legend("topleft", legend = colnames(err), lwd = 3, col = 1:3)
```

## Problem 2 
Now I used different $\Delta S$ to test for the results. From the plots, we can see that the errors get larger when the option moves to **out-of-the-money**. 

$\Delta S = 1$:
```{R echo = FALSE}
# set parameters
s0 <- 10
k <- 10
r <- 0.04
sig <- 0.2
t <- 0.5
dt <- 0.002
ds <- 1

# i. Values
# (a) Explicit Finite-Difference Method
Ca <- efd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pa <- efd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# (b) Implicit Finite-Difference Method
Cb <- ifd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pb <- ifd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# (c) Crank-Nicolson Finite-Difference Method
Cc <- cnfd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pc <- cnfd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# output
cbind(EFD = c(call = Ca, put = Pa), IFD = c(Cb, Pb), CNFE = c(Cc, Pc))

# ii. Graphs
s0 <- 4:16
c_edf2 <- c_idf2 <- c_cndf2 <- vector()
p_edf2 <- p_idf2 <- p_cndf2 <- vector()
for (i in 1:length(s0)){
  # calls
  c_edf2[i] <- efd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  c_idf2[i] <- ifd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  c_cndf2[i] <- cnfd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  # puts
  p_edf2[i] <- efd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  p_idf2[i] <- ifd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  p_cndf2[i] <- cnfd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
}
matplot(s0, cbind(c_edf2, c_idf2, c_cndf2), type ="l", lwd = 1, lty=1,
        main = "Call Prices", xlab = "Stock price", ylab = "Call Price")
legend("topleft", legend = c("EDF", "IDF", "CNDF"), lwd = 1, col = 1:3)
matplot(s0, cbind(p_edf2, p_idf2, p_cndf2), type ="l", lwd = 1, lty=1,
        main = "Put Prices", xlab = "Stock price", ylab = "Put Price")
legend("topright", legend = c("EDF", "IDF", "CNDF"), lwd = 1, col = 1:3)
```


$\Delta S = 1.25$
```{R echo = FALSE}
# set parameters
s0 <- 10
k <- 10
r <- 0.04
sig <- 0.2
t <- 0.5
dt <- 0.002
ds <- 1.25

# i. Values
# (a) Explicit Finite-Difference Method
Ca <- efd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pa <- efd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# (b) Implicit Finite-Difference Method
Cb <- ifd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pb <- ifd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# (c) Crank-Nicolson Finite-Difference Method
Cc <- cnfd(type="call", euro=F, s0, k, r, sig, t, dt, ds, log=F)
Pc <- cnfd(type="put", euro=F, s0, k, r, sig, t, dt, ds, log=F)
# output
cbind(EFD = c(call = Ca, put = Pa), IFD = c(Cb, Pb), CNFE = c(Cc, Pc))

# ii. Graphs
s0 <- 4:16
c_edf2 <- c_idf2 <- c_cndf2 <- vector()
p_edf2 <- p_idf2 <- p_cndf2 <- vector()
for (i in 1:length(s0)){
  # calls
  c_edf2[i] <- efd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  c_idf2[i] <- ifd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  c_cndf2[i] <- cnfd(type="call", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  # puts
  p_edf2[i] <- efd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  p_idf2[i] <- ifd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
  p_cndf2[i] <- cnfd(type="put", euro=F, s0[i], k, r, sig, t, dt, ds, log=F)
}
matplot(s0, cbind(c_edf2, c_idf2, c_cndf2), type ="l", lwd = 1, lty=1,
        main = "Call Prices", xlab = "Stock price", ylab = "Call Price")
legend("topleft", legend = c("EDF", "IDF", "CNDF"), lwd = 1, col = 1:3)
matplot(s0, cbind(p_edf2, p_idf2, p_cndf2), type ="l", lwd = 1, lty=1,
        main = "Put Prices", xlab = "Stock price", ylab = "Put Price")
legend("topright", legend = c("EDF", "IDF", "CNDF"), lwd = 1, col = 1:3)
```
# Code
## bsm.r
```{R eval = FALSE}
# Black-schole pricing model for European options
bsCall <- function(s0,t,x,r,sigma){
  # compute d1, d2
  d1 <- (log(s0/x)+(r+sigma^2/2)*t)/(sigma*sqrt(t))
  d2 <- d1-sigma*sqrt(t)
  # output: Black-Sholes price
  c_bs <- s0*pnorm(d1)-x*exp(-r*t)*pnorm(d2) 
  return(c_bs)
}
bsPut <- function(s0,t,x,r,sigma){
  # compute d1, d2
  d1 <- (log(s0/x)+(r+sigma^2/2)*t)/(sigma*sqrt(t))
  d2 <- d1-sigma*sqrt(t)
  # output: Black-Sholes price
  p_bs <- x*exp(-r*t)*pnorm(-d2)-s0*pnorm(-d1) 
  return(p_bs)
}
```
## finiteDiff.r
```{R eval = FALSE}
# Explicit Finite-Difference Method 
efd <- function(type, euro, s0, k, r, sig, t, dt, dsx, log){
  # if change in log price
  if (log) {
    n <- floor(log(s0)/dsx)
    # defind M and N
    M <- t/dt+1
    N <- 2*n+1
    # define dx
    dx <- dsx
    # find terminal conditions
    sT <- exp(c(log(s0)+dx*(n:-n)))
    # calculate pu, pm, pd
    pu <- dt*(sig^2/(2*dx^2) + (r-sig^2/2)/(2*dx))
    pm <- 1 - dt*sig^2/dx^2 - r*dt
    pd <- dt*(sig^2/(2*dx^2) - (r-sig^2/2)/(2*dx))
    # construct matrix A
    A <- diag(pm, N-2, N-2)
    diag(A[-1,]) <- pu
    diag(A[,-1]) <- pd
    # set offset constans
    b <- c(pu, pd)
  } else { # if change in price
    # defind M
    M <- t/dt+1
    # define ds
    ds <- dsx
    # find terminal conditions
    sT <- seq(2*s0, 0, -ds)
    N <- length(sT)
    # calculate pu, pm, pd
    j <- (N-2):1
    pu <- 0.5*dt*(sig^2*j^2 + r*j)
    pm <- 1-dt*(sig^2*j^2+r)
    pd <- 0.5*dt*(sig^2*j^2 - r*j)
    # set A
    A <- diag(pm)
    diag(A[-1,]) <- pu[2:length(pu)]
    diag(A[,-1]) <- pd[1:length(pd)-1]
    # set offset constans
    b <- c(pu[1], pd[length(pd)])
  }
  # payoff matrix
  payoff <- diag(0, N, M)
  if (type == "call"){
    payoff[,M] <- ifelse(sT-k>0, sT-k, 0)
    payoff[1,] <- (max(sT)-k)*exp(-r*seq(t,0,-dt))
    payoff[N,] <- 0
  } 
  else if (type == "put"){
    payoff[,M] <- ifelse(k-sT>0, k-sT, 0)
    payoff[1,] <- 0
    payoff[N,] <- (k-min(sT))*exp(-r*seq(t,0,-dt))
  } 
  else{
    stop("Incorrect option type!")
  }
  # for loop through M
  for (i in (M-1):1){
    # if Europian option
    if (euro){
      payoff[2:(N-1),i] <- A%*%payoff[2:(N-1),i+1]
      payoff[2,i] <- payoff[2,i]+b[1]*payoff[1,i+1]
      payoff[N-1,i] <- payoff[N-1,i]+b[2]*payoff[N,i+1]
    } else { # if American option
      cv <- payoff[,i]
      cv[2:(N-1)] <- A%*%payoff[2:(N-1),i+1]
      cv[2] <- payoff[2,i]+b[1]*payoff[1,i+1]
      cv[N-1] <- payoff[N-1,i]+b[2]*payoff[N,i+1]
      payoff[,i] <- apply(cbind(payoff[,M], cv),1,max)
    }
  }
  return(payoff[floor(N/2)+1,1])
}
# Implicit Finite-Difference Method
ifd <- function(type, euro, s0, k, r, sig, t, dt, dsx, log){
  # if change in log price
  if (log) {
    n <- floor(log(s0)/dsx)
    # defind M and N
    M <- t/dt+1
    N <- 2*n+1
    # define dx
    dx <- dsx
    # find terminal conditions
    sT <- exp(c(log(s0)+dx*(n:-n)))
    # calculate pu, pm, pd
    pu = -0.5*dt*(sig^2/dx^2 + (r-sig^2/2)/dx)
    pm = 1 + dt*sig^2/dx^2 + r*dt
    pd = -0.5*dt*(sig^2/dx^2 - (r-sig^2/2)/dx)
    # construct matrix A
    A <- diag(pm, N-2, N-2)
    diag(A[-1,]) <- pu
    diag(A[,-1]) <- pd
    A <- rbind(c(1, -1, rep(0,N-2)), 
               cbind(c(pu, rep(0,N-3)),A,c(rep(0,N-3), pd)), 
               c(rep(0,N-2), 1, -1))
  } else { # if change in price
    # defind M
    M <- t/dt+1
    # define ds
    ds <- dsx
    # find terminal conditions
    sT <- seq(2*s0, 0, -ds)
    N <- length(sT)
    # calculate pu, pm, pd
    j <- (N-2):1
    pu <- -0.5*dt*(sig^2*j^2 + r*j)
    pm <- 1+dt*(sig^2*j^2+r)
    pd <- 0.5*dt*(-sig^2*j^2 + r*j)
    # set A
    A <- diag(pm)
    diag(A[-1,]) <- pu[2:length(pu)]
    diag(A[,-1]) <- pd[1:length(pd)-1]
    # set offset constans
    b <- c(-pu[1], -pd[length(pd)])
  }
  # payoff matrix
  payoff <- diag(0, N, M)
  if (type == "call"){
    payoff[,M] <- ifelse(sT-k>0, sT-k, 0)
    payoff[1,] <- (max(sT)-k)*exp(-r*seq(t,0,-dt))
    payoff[N,] <- 0
  } 
  else if (type == "put"){
    payoff[,M] <- ifelse(k-sT>0, k-sT, 0)
    payoff[1,] <- 0
    payoff[N,] <- (k-min(sT))*exp(-r*seq(t,0,-dt))
  } 
  else{
    stop("Incorrect option type!")
  }
  # find A inverse
  Ainv <- solve(A)
  # find option price
  if (log) {
    for (i in (M-1):1){
      # construct matrix B
      B <- payoff[,i+1]
      # if Europian option
      if (euro){
        payoff[,i] <- Ainv%*%B
      } else { # if American option
        cv <- Ainv%*%B
        payoff[,i] <- apply(cbind(payoff[,M], cv),1,max)
      }
    }
  } else {
    # for loop through M
    for (i in (M-1):1){
      # construct matrix B
      B <- payoff[2:(N-1),i+1]
      B[1] <- B[1] + payoff[1,i+1]*b[1]
      B[length(N)] <- B[length(N)] + payoff[N,i+1]*b[2]
      # if Europian option
      if (euro){
        payoff[2:(N-1),i] <- Ainv%*%B
      } else { # if American option
        cv <- payoff[,i]
        cv[2:(N-1)] <- Ainv%*%B
        payoff[,i] <- apply(cbind(payoff[,M], cv),1,max)
      }
    }
  }
  return(payoff[floor(N/2)+1,1])
}
# Crank-Nicolson Finite-Difference Method
cnfd <- function(type, euro, s0, k, r, sig, t, dt, dsx, log){
  # if change in log price
  if (log) {
    n <- floor(log(s0)/dsx)
    # defind M and N
    M <- t/dt+1
    N <- 2*n+1
    # define dx
    dx <- dsx
    # find terminal conditions
    sT <- exp(c(log(s0)+dx*(n:-n)))
    # calculate pu, pm, pd
    pu = -0.25*dt*(sig^2/dx^2 + (r-sig^2/2)/dx)
    pm = 1 + dt*sig^2/(2*dx^2) + r*dt/2
    pd = -0.25*dt*(sig^2/dx^2 - (r-sig^2/2)/dx)
    # construct matrix A
    A <- diag(pm, N-2, N-2)
    diag(A[-1,]) <- pu
    diag(A[,-1]) <- pd
    A <- rbind(c(1, -1, rep(0,N-2)), 
               cbind(c(pu, rep(0,N-3)),A,c(rep(0,N-3), pd)), 
               c(rep(0,N-2), 1, -1))
  } else { # if change in price
    # defind M
    M <- t/dt+1
    # define ds
    ds <- dsx
    # find terminal conditions
    sT <- seq(2*s0, 0, -ds)
    N <- length(sT)
    # calculate pu, pm, pd
    j <- (N-2):1
    pu <- 0.25*dt*(sig^2*j^2 + r*j)
    pm <- -0.5*dt*(sig^2*j^2+r)
    pd <- 0.25*dt*(sig^2*j^2 - r*j)
    # set C
    A <- diag(1-pm)
    diag(A[-1,]) <- -pu[2:length(pu)]
    diag(A[,-1]) <- -pd[1:length(pd)-1]
    # set D
    D <- diag(1+pm)
    diag(D[-1,]) <- pu[2:length(pu)]
    diag(D[,-1]) <- pd[1:length(pd)-1]
    # set offset constans
    b <- c(pu[1], pd[length(pd)])
  }
  # payoff matrix
  payoff <- diag(0, N, M)
  if (type == "call"){
    payoff[,M] <- ifelse(sT-k>0, sT-k, 0)
    payoff[1,] <- (max(sT)-k)*exp(-r*seq(t,0,-dt))
    payoff[N,] <- 0
  } 
  else if (type == "put"){
    payoff[,M] <- ifelse(k-sT>0, k-sT, 0)
    payoff[1,] <- 0
    payoff[N,] <- (k-min(sT))*exp(-r*seq(t,0,-dt))
  } 
  else{
    stop("Incorrect option type!")
  }
  # find A inverse
  Ainv <- solve(A)
  # find option price
  if (log) {
    for (i in (M-1):1){
      # construct matrix B
      B <- payoff[,i+1]
      B[2:(N-1)] <- -pu*payoff[1:(N-2),i+1] - (pm-2)*payoff[2:(N-1),i+1] - pd*payoff[3:N,i+1] 
      # if Europian option
      if (euro){
        payoff[,i] <- Ainv%*%B
      } else { # if American option
        cv <- Ainv%*%B
        payoff[,i] <- apply(cbind(payoff[,M], cv),1,max)
      }
    }
  } else {
    # for loop through M
    for (i in (M-1):1){
      # construct matrix B
      B <- D%*%payoff[2:(N-1),i+1]
      B[1] <- B[1] + payoff[1,i+1]*b[1] + payoff[1,i]*b[1]
      B[length(N)] <- B[length(N)] + payoff[N,i+1]*b[2] + payoff[N,i+1]*b[2]
      # if Europian option
      if (euro){
        payoff[2:(N-1),i] <- Ainv%*%B
      } else { # if American option
        cv <- payoff[,i]
        cv[2:(N-1)] <- Ainv%*%B
        payoff[,i] <- apply(cbind(payoff[,M], cv),1,max)
      }
    }
  }
  return(payoff[floor(N/2)+1,1])
}

```